CREATE TABLE IF NOT EXISTS sessions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	guild_id TEXT NOT NULL,
	channel_id TEXT NOT NULL,
	started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	seconds_elapsed INTEGER,
	status INTEGER,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);